// Copyright (c) 2018 Anki, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License in the file LICENSE.txt or at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Behavior related messages

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: behavior.proto

package Anki_Vector_external_interface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Where in the behavior tree the SDK code should be executed.
type ControlRequest_Priority int32

const (
	// Unknown priority. Used for versions that don't understand old priority levels.
	ControlRequest_UNKNOWN ControlRequest_Priority = 0
	// Highest priority level. Suppresses most automatic physical reactions, use with caution.
	ControlRequest_OVERRIDE_BEHAVIORS ControlRequest_Priority = 10
	// Normal priority level. Directly under mandatory physical reactions.
	ControlRequest_DEFAULT ControlRequest_Priority = 20
	// Enable long-running SDK control between script execution.  Not to be used for regular behavior control.
	ControlRequest_RESERVE_CONTROL ControlRequest_Priority = 30
)

// Enum value maps for ControlRequest_Priority.
var (
	ControlRequest_Priority_name = map[int32]string{
		0:  "UNKNOWN",
		10: "OVERRIDE_BEHAVIORS",
		20: "DEFAULT",
		30: "RESERVE_CONTROL",
	}
	ControlRequest_Priority_value = map[string]int32{
		"UNKNOWN":            0,
		"OVERRIDE_BEHAVIORS": 10,
		"DEFAULT":            20,
		"RESERVE_CONTROL":    30,
	}
)

func (x ControlRequest_Priority) Enum() *ControlRequest_Priority {
	p := new(ControlRequest_Priority)
	*p = x
	return p
}

func (x ControlRequest_Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlRequest_Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_behavior_proto_enumTypes[0].Descriptor()
}

func (ControlRequest_Priority) Type() protoreflect.EnumType {
	return &file_behavior_proto_enumTypes[0]
}

func (x ControlRequest_Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlRequest_Priority.Descriptor instead.
func (ControlRequest_Priority) EnumDescriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{1, 0}
}

// Tell the behavior stream to release control from the SDK.
// The stream may stay alive, but Vector will be allowed to run
// his normal behaviors.
type ControlRelease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRelease) Reset() {
	*x = ControlRelease{}
	mi := &file_behavior_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRelease) ProtoMessage() {}

func (x *ControlRelease) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRelease.ProtoReflect.Descriptor instead.
func (*ControlRelease) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{0}
}

// Request control of the behavior system at a given priority.
// Currently there is only one priority level.
type ControlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where in the behavior tree the SDK code should be executed.
	Priority      ControlRequest_Priority `protobuf:"varint,1,opt,name=priority,proto3,enum=Anki.Vector.external_interface.ControlRequest_Priority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_behavior_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{1}
}

func (x *ControlRequest) GetPriority() ControlRequest_Priority {
	if x != nil {
		return x.Priority
	}
	return ControlRequest_UNKNOWN
}

// Messages that can be sent to the behavior stream. Explicitly
// requesting or releasing control.
type BehaviorControlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*BehaviorControlRequest_ControlRelease
	//	*BehaviorControlRequest_ControlRequest
	RequestType   isBehaviorControlRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BehaviorControlRequest) Reset() {
	*x = BehaviorControlRequest{}
	mi := &file_behavior_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BehaviorControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BehaviorControlRequest) ProtoMessage() {}

func (x *BehaviorControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BehaviorControlRequest.ProtoReflect.Descriptor instead.
func (*BehaviorControlRequest) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{2}
}

func (x *BehaviorControlRequest) GetRequestType() isBehaviorControlRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *BehaviorControlRequest) GetControlRelease() *ControlRelease {
	if x != nil {
		if x, ok := x.RequestType.(*BehaviorControlRequest_ControlRelease); ok {
			return x.ControlRelease
		}
	}
	return nil
}

func (x *BehaviorControlRequest) GetControlRequest() *ControlRequest {
	if x != nil {
		if x, ok := x.RequestType.(*BehaviorControlRequest_ControlRequest); ok {
			return x.ControlRequest
		}
	}
	return nil
}

type isBehaviorControlRequest_RequestType interface {
	isBehaviorControlRequest_RequestType()
}

type BehaviorControlRequest_ControlRelease struct {
	// Release control of the behavior system back to Vector.
	ControlRelease *ControlRelease `protobuf:"bytes,1,opt,name=control_release,json=controlRelease,proto3,oneof"`
}

type BehaviorControlRequest_ControlRequest struct {
	// Request control of the behavior system for the SDK.
	ControlRequest *ControlRequest `protobuf:"bytes,2,opt,name=control_request,json=controlRequest,proto3,oneof"`
}

func (*BehaviorControlRequest_ControlRelease) isBehaviorControlRequest_RequestType() {}

func (*BehaviorControlRequest_ControlRequest) isBehaviorControlRequest_RequestType() {}

// The SDK user is now free to run any actions and behaviors they like.
// Until a ControlLostResponse is received, they are directly in control
// of Vector's behavior system.
type ControlGrantedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlGrantedResponse) Reset() {
	*x = ControlGrantedResponse{}
	mi := &file_behavior_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlGrantedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlGrantedResponse) ProtoMessage() {}

func (x *ControlGrantedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlGrantedResponse.ProtoReflect.Descriptor instead.
func (*ControlGrantedResponse) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{3}
}

// This informs the user that they lost control of the behavior system.
// All direct actions will be unavailable via the sdk until control is regained.
// Regaining control can be either through a call to ControlRequest, or
// can be as a result of conditions passed to the original ControlRequest.
type ControlLostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlLostResponse) Reset() {
	*x = ControlLostResponse{}
	mi := &file_behavior_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlLostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlLostResponse) ProtoMessage() {}

func (x *ControlLostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlLostResponse.ProtoReflect.Descriptor instead.
func (*ControlLostResponse) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{4}
}

// The ability to reserve control before/after SDK scripts has been lost.
// This control can be regained through another ControlRequest.
type ReservedControlLostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservedControlLostResponse) Reset() {
	*x = ReservedControlLostResponse{}
	mi := &file_behavior_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservedControlLostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservedControlLostResponse) ProtoMessage() {}

func (x *ReservedControlLostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservedControlLostResponse.ProtoReflect.Descriptor instead.
func (*ReservedControlLostResponse) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{5}
}

// Responses from the behavior stream.
type BehaviorControlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ResponseType:
	//
	//	*BehaviorControlResponse_ControlGrantedResponse
	//	*BehaviorControlResponse_ControlLostEvent
	//	*BehaviorControlResponse_KeepAlive
	//	*BehaviorControlResponse_ReservedControlLostEvent
	ResponseType  isBehaviorControlResponse_ResponseType `protobuf_oneof:"response_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BehaviorControlResponse) Reset() {
	*x = BehaviorControlResponse{}
	mi := &file_behavior_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BehaviorControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BehaviorControlResponse) ProtoMessage() {}

func (x *BehaviorControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BehaviorControlResponse.ProtoReflect.Descriptor instead.
func (*BehaviorControlResponse) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{6}
}

func (x *BehaviorControlResponse) GetResponseType() isBehaviorControlResponse_ResponseType {
	if x != nil {
		return x.ResponseType
	}
	return nil
}

func (x *BehaviorControlResponse) GetControlGrantedResponse() *ControlGrantedResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*BehaviorControlResponse_ControlGrantedResponse); ok {
			return x.ControlGrantedResponse
		}
	}
	return nil
}

func (x *BehaviorControlResponse) GetControlLostEvent() *ControlLostResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*BehaviorControlResponse_ControlLostEvent); ok {
			return x.ControlLostEvent
		}
	}
	return nil
}

func (x *BehaviorControlResponse) GetKeepAlive() *KeepAlivePing {
	if x != nil {
		if x, ok := x.ResponseType.(*BehaviorControlResponse_KeepAlive); ok {
			return x.KeepAlive
		}
	}
	return nil
}

func (x *BehaviorControlResponse) GetReservedControlLostEvent() *ReservedControlLostResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*BehaviorControlResponse_ReservedControlLostEvent); ok {
			return x.ReservedControlLostEvent
		}
	}
	return nil
}

type isBehaviorControlResponse_ResponseType interface {
	isBehaviorControlResponse_ResponseType()
}

type BehaviorControlResponse_ControlGrantedResponse struct {
	// The SDK user is now free to directly control Vector.
	ControlGrantedResponse *ControlGrantedResponse `protobuf:"bytes,1,opt,name=control_granted_response,json=controlGrantedResponse,proto3,oneof"`
}

type BehaviorControlResponse_ControlLostEvent struct {
	// Control of the behavior system has been lost to a higher priority behavior.
	ControlLostEvent *ControlLostResponse `protobuf:"bytes,2,opt,name=control_lost_event,json=controlLostEvent,proto3,oneof"`
}

type BehaviorControlResponse_KeepAlive struct {
	// Used by Vector to verify the connection is still alive.
	KeepAlive *KeepAlivePing `protobuf:"bytes,3,opt,name=keep_alive,json=keepAlive,proto3,oneof"`
}

type BehaviorControlResponse_ReservedControlLostEvent struct {
	// Behavior system lock has been lost to another connection
	ReservedControlLostEvent *ReservedControlLostResponse `protobuf:"bytes,4,opt,name=reserved_control_lost_event,json=reservedControlLostEvent,proto3,oneof"`
}

func (*BehaviorControlResponse_ControlGrantedResponse) isBehaviorControlResponse_ResponseType() {}

func (*BehaviorControlResponse_ControlLostEvent) isBehaviorControlResponse_ResponseType() {}

func (*BehaviorControlResponse_KeepAlive) isBehaviorControlResponse_ResponseType() {}

func (*BehaviorControlResponse_ReservedControlLostEvent) isBehaviorControlResponse_ResponseType() {}

var File_behavior_proto protoreflect.FileDescriptor

const file_behavior_proto_rawDesc = "" +
	"\n" +
	"\x0ebehavior.proto\x12\x1eAnki.Vector.external_interface\x1a\x0emessages.proto\"\x10\n" +
	"\x0eControlRelease\"\xb8\x01\n" +
	"\x0eControlRequest\x12S\n" +
	"\bpriority\x18\x01 \x01(\x0e27.Anki.Vector.external_interface.ControlRequest.PriorityR\bpriority\"Q\n" +
	"\bPriority\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x16\n" +
	"\x12OVERRIDE_BEHAVIORS\x10\n" +
	"\x12\v\n" +
	"\aDEFAULT\x10\x14\x12\x13\n" +
	"\x0fRESERVE_CONTROL\x10\x1e\"\xde\x01\n" +
	"\x16BehaviorControlRequest\x12Y\n" +
	"\x0fcontrol_release\x18\x01 \x01(\v2..Anki.Vector.external_interface.ControlReleaseH\x00R\x0econtrolRelease\x12Y\n" +
	"\x0fcontrol_request\x18\x02 \x01(\v2..Anki.Vector.external_interface.ControlRequestH\x00R\x0econtrolRequestB\x0e\n" +
	"\frequest_type\"\x18\n" +
	"\x16ControlGrantedResponse\"\x15\n" +
	"\x13ControlLostResponse\"\x1d\n" +
	"\x1bReservedControlLostResponse\"\xd1\x03\n" +
	"\x17BehaviorControlResponse\x12r\n" +
	"\x18control_granted_response\x18\x01 \x01(\v26.Anki.Vector.external_interface.ControlGrantedResponseH\x00R\x16controlGrantedResponse\x12c\n" +
	"\x12control_lost_event\x18\x02 \x01(\v23.Anki.Vector.external_interface.ControlLostResponseH\x00R\x10controlLostEvent\x12N\n" +
	"\n" +
	"keep_alive\x18\x03 \x01(\v2-.Anki.Vector.external_interface.KeepAlivePingH\x00R\tkeepAlive\x12|\n" +
	"\x1breserved_control_lost_event\x18\x04 \x01(\v2;.Anki.Vector.external_interface.ReservedControlLostResponseH\x00R\x18reservedControlLostEventB\x0f\n" +
	"\rresponse_typeB Z\x1eAnki.Vector.external_interfaceb\x06proto3"

var (
	file_behavior_proto_rawDescOnce sync.Once
	file_behavior_proto_rawDescData []byte
)

func file_behavior_proto_rawDescGZIP() []byte {
	file_behavior_proto_rawDescOnce.Do(func() {
		file_behavior_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_behavior_proto_rawDesc), len(file_behavior_proto_rawDesc)))
	})
	return file_behavior_proto_rawDescData
}

var file_behavior_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_behavior_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_behavior_proto_goTypes = []any{
	(ControlRequest_Priority)(0),        // 0: Anki.Vector.external_interface.ControlRequest.Priority
	(*ControlRelease)(nil),              // 1: Anki.Vector.external_interface.ControlRelease
	(*ControlRequest)(nil),              // 2: Anki.Vector.external_interface.ControlRequest
	(*BehaviorControlRequest)(nil),      // 3: Anki.Vector.external_interface.BehaviorControlRequest
	(*ControlGrantedResponse)(nil),      // 4: Anki.Vector.external_interface.ControlGrantedResponse
	(*ControlLostResponse)(nil),         // 5: Anki.Vector.external_interface.ControlLostResponse
	(*ReservedControlLostResponse)(nil), // 6: Anki.Vector.external_interface.ReservedControlLostResponse
	(*BehaviorControlResponse)(nil),     // 7: Anki.Vector.external_interface.BehaviorControlResponse
	(*KeepAlivePing)(nil),               // 8: Anki.Vector.external_interface.KeepAlivePing
}
var file_behavior_proto_depIdxs = []int32{
	0, // 0: Anki.Vector.external_interface.ControlRequest.priority:type_name -> Anki.Vector.external_interface.ControlRequest.Priority
	1, // 1: Anki.Vector.external_interface.BehaviorControlRequest.control_release:type_name -> Anki.Vector.external_interface.ControlRelease
	2, // 2: Anki.Vector.external_interface.BehaviorControlRequest.control_request:type_name -> Anki.Vector.external_interface.ControlRequest
	4, // 3: Anki.Vector.external_interface.BehaviorControlResponse.control_granted_response:type_name -> Anki.Vector.external_interface.ControlGrantedResponse
	5, // 4: Anki.Vector.external_interface.BehaviorControlResponse.control_lost_event:type_name -> Anki.Vector.external_interface.ControlLostResponse
	8, // 5: Anki.Vector.external_interface.BehaviorControlResponse.keep_alive:type_name -> Anki.Vector.external_interface.KeepAlivePing
	6, // 6: Anki.Vector.external_interface.BehaviorControlResponse.reserved_control_lost_event:type_name -> Anki.Vector.external_interface.ReservedControlLostResponse
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_behavior_proto_init() }
func file_behavior_proto_init() {
	if File_behavior_proto != nil {
		return
	}
	file_messages_proto_init()
	file_behavior_proto_msgTypes[2].OneofWrappers = []any{
		(*BehaviorControlRequest_ControlRelease)(nil),
		(*BehaviorControlRequest_ControlRequest)(nil),
	}
	file_behavior_proto_msgTypes[6].OneofWrappers = []any{
		(*BehaviorControlResponse_ControlGrantedResponse)(nil),
		(*BehaviorControlResponse_ControlLostEvent)(nil),
		(*BehaviorControlResponse_KeepAlive)(nil),
		(*BehaviorControlResponse_ReservedControlLostEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_behavior_proto_rawDesc), len(file_behavior_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_behavior_proto_goTypes,
		DependencyIndexes: file_behavior_proto_depIdxs,
		EnumInfos:         file_behavior_proto_enumTypes,
		MessageInfos:      file_behavior_proto_msgTypes,
	}.Build()
	File_behavior_proto = out.File
	file_behavior_proto_goTypes = nil
	file_behavior_proto_depIdxs = nil
}
