// Copyright (c) 2018 Anki, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License in the file LICENSE.txt or at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Response status

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: response_status.proto

package Anki_Vector_external_interface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseStatus_StatusCode int32

const (
	ResponseStatus_UNKNOWN ResponseStatus_StatusCode = 0
	// The message has completed as expected.
	ResponseStatus_RESPONSE_RECEIVED ResponseStatus_StatusCode = 1
	// The message has been sent to the robot.
	ResponseStatus_REQUEST_PROCESSING ResponseStatus_StatusCode = 2
	// The message has been handled successfully at the interface level.
	ResponseStatus_OK ResponseStatus_StatusCode = 3
	// The user was not authorizied.
	ResponseStatus_FORBIDDEN ResponseStatus_StatusCode = 100
	// The requested attribute was not found.
	ResponseStatus_NOT_FOUND ResponseStatus_StatusCode = 101
	// Currently updating values from another call.
	ResponseStatus_ERROR_UPDATE_IN_PROGRESS ResponseStatus_StatusCode = 102
)

// Enum value maps for ResponseStatus_StatusCode.
var (
	ResponseStatus_StatusCode_name = map[int32]string{
		0:   "UNKNOWN",
		1:   "RESPONSE_RECEIVED",
		2:   "REQUEST_PROCESSING",
		3:   "OK",
		100: "FORBIDDEN",
		101: "NOT_FOUND",
		102: "ERROR_UPDATE_IN_PROGRESS",
	}
	ResponseStatus_StatusCode_value = map[string]int32{
		"UNKNOWN":                  0,
		"RESPONSE_RECEIVED":        1,
		"REQUEST_PROCESSING":       2,
		"OK":                       3,
		"FORBIDDEN":                100,
		"NOT_FOUND":                101,
		"ERROR_UPDATE_IN_PROGRESS": 102,
	}
)

func (x ResponseStatus_StatusCode) Enum() *ResponseStatus_StatusCode {
	p := new(ResponseStatus_StatusCode)
	*p = x
	return p
}

func (x ResponseStatus_StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus_StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_response_status_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus_StatusCode) Type() protoreflect.EnumType {
	return &file_response_status_proto_enumTypes[0]
}

func (x ResponseStatus_StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus_StatusCode.Descriptor instead.
func (ResponseStatus_StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_response_status_proto_rawDescGZIP(), []int{0, 0}
}

// A shared response message sent back as part of most requests.
// This will indicate the generic state of the request.
type ResponseStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The generic status code to give high-level insight into the progress of a
	// given message.
	Code          ResponseStatus_StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=Anki.Vector.external_interface.ResponseStatus_StatusCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseStatus) Reset() {
	*x = ResponseStatus{}
	mi := &file_response_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatus) ProtoMessage() {}

func (x *ResponseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_response_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatus.ProtoReflect.Descriptor instead.
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return file_response_status_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseStatus) GetCode() ResponseStatus_StatusCode {
	if x != nil {
		return x.Code
	}
	return ResponseStatus_UNKNOWN
}

var File_response_status_proto protoreflect.FileDescriptor

const file_response_status_proto_rawDesc = "" +
	"\n" +
	"\x15response_status.proto\x12\x1eAnki.Vector.external_interface\"\xee\x01\n" +
	"\x0eResponseStatus\x12M\n" +
	"\x04code\x18\x01 \x01(\x0e29.Anki.Vector.external_interface.ResponseStatus.StatusCodeR\x04code\"\x8c\x01\n" +
	"\n" +
	"StatusCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x15\n" +
	"\x11RESPONSE_RECEIVED\x10\x01\x12\x16\n" +
	"\x12REQUEST_PROCESSING\x10\x02\x12\x06\n" +
	"\x02OK\x10\x03\x12\r\n" +
	"\tFORBIDDEN\x10d\x12\r\n" +
	"\tNOT_FOUND\x10e\x12\x1c\n" +
	"\x18ERROR_UPDATE_IN_PROGRESS\x10fB Z\x1eAnki.Vector.external_interfaceb\x06proto3"

var (
	file_response_status_proto_rawDescOnce sync.Once
	file_response_status_proto_rawDescData []byte
)

func file_response_status_proto_rawDescGZIP() []byte {
	file_response_status_proto_rawDescOnce.Do(func() {
		file_response_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_status_proto_rawDesc), len(file_response_status_proto_rawDesc)))
	})
	return file_response_status_proto_rawDescData
}

var file_response_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_response_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_status_proto_goTypes = []any{
	(ResponseStatus_StatusCode)(0), // 0: Anki.Vector.external_interface.ResponseStatus.StatusCode
	(*ResponseStatus)(nil),         // 1: Anki.Vector.external_interface.ResponseStatus
}
var file_response_status_proto_depIdxs = []int32{
	0, // 0: Anki.Vector.external_interface.ResponseStatus.code:type_name -> Anki.Vector.external_interface.ResponseStatus.StatusCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_response_status_proto_init() }
func file_response_status_proto_init() {
	if File_response_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_status_proto_rawDesc), len(file_response_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_status_proto_goTypes,
		DependencyIndexes: file_response_status_proto_depIdxs,
		EnumInfos:         file_response_status_proto_enumTypes,
		MessageInfos:      file_response_status_proto_msgTypes,
	}.Build()
	File_response_status_proto = out.File
	file_response_status_proto_goTypes = nil
	file_response_status_proto_depIdxs = nil
}
